name: build-miz-master
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
jobs:
  build-mission-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'deploy CI scripts'
        run: npm install
      - name: 'force mission version with git tag'
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm run jtff-version $GITHUB_REF_NAME
      - name: 'Do Release'
        run: |
          npm run jtff-release
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "skip(ci): freeze version"
          git push origin master
      - name: 'build missions'
        run: npm run build
      - name: 'Tag version'
        if: !(startsWith(github.ref, 'refs/tags/'))
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag `jq -r .general.missionVersion config.json`
          git push origin HEAD:master --tags
      - name: 'stores mission files'
        uses: actions/upload-artifact@v2
        with:
          name: missionFiles
          path: dist/*.miz
      - name: 'Prepare next version'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          git merge --no-ff master
          npm run jtff-nextversion
          git add .
          git commit -m "skip(ci): prepare next version"
          git push origin HEAD:develop
